# Build a slim zip of PINE for sharing (target: well under 500 MB when datasets/runs are excluded).
# Uses .NET ZipFile (more reliable than Compress-Archive for deep trees / many files).
#
# Excludes (among others): .git, build outputs, Android NDK CMake caches (.cxx), local.properties,
# IDE (.idea), JVM crash logs, Flutter ephemeral plugin trees, datasets (except a stub data.yaml).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File D:\PINE\scripts\make_agent_bundle.ps1
#   powershell -File .\scripts\make_agent_bundle.ps1 -OutputZip D:\PINE-agent.zip

param(
    [string] $ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string] $OutputZip = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot "..")).Path "PINE-agent-bundle.zip")
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.IO.Compression.FileSystem

# Short path on the project drive avoids MAX_PATH when zipping deep plugin_symlinks trees.
$staging = Join-Path $ProjectRoot ("_bz_" + [Guid]::NewGuid().ToString("n").Substring(0, 12))
$robolog = Join-Path $env:TEMP ("pine_rb_" + [Guid]::NewGuid().ToString("n") + ".log")

Write-Host "Project: $ProjectRoot"
Write-Host "Staging: $staging"
Write-Host "Output:  $OutputZip"

if (-not (Test-Path $ProjectRoot)) {
    throw "Project root not found: $ProjectRoot"
}

try {
    $stagingLeaf = Split-Path -Leaf $staging

    # /E copy subdirs, /XD exclude dirs (relative to source), /XF exclude file patterns
    $excludeDirs = [System.Collections.Generic.List[string]]::new()
    foreach ($d in @(
        ".git", ".cursor", ".dart_tool", ".venv", "venv", "env", "build", "runs", "datasets",
        "android\build", "android\app\build", "android\.gradle", ".gradle",
        # NDK / CMake: huge, machine-local; regenerated on build.
        "android\app\.cxx",
        "android\app\.externalNativeBuild",
        "android\.kotlin",
        "ios\Pods", "ios\build",
        "node_modules",
        "android_backup_final",
        ".idea",
        # Flutter toolchains: ephemeral holds .plugin_symlinks → plugin *examples* with huge paths;
        # regenerated by `flutter pub get`. Omit from agent zips.
        "windows\flutter\ephemeral",
        "linux\flutter\ephemeral",
        "macos\Flutter\ephemeral",
        "ios\Flutter\ephemeral"
    )) {
        $excludeDirs.Add($d) | Out-Null
    }

    # Leftover _bz_* dirs from interrupted runs — list BEFORE creating this run's staging folder.
    Get-ChildItem -LiteralPath $ProjectRoot -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like "_bz_*" } |
        ForEach-Object {
            Write-Host "Excluding bundle staging leftover: $($_.Name)"
            $excludeDirs.Add($_.Name) | Out-Null
        }

    New-Item -ItemType Directory -Path $staging -Force | Out-Null

    # Empty staging dir sits under project root; do not copy it into the zip tree.
    if (-not $excludeDirs.Contains($stagingLeaf)) {
        $excludeDirs.Add($stagingLeaf) | Out-Null
    }

    # Roboflow/dataset backups: huge, not needed for agents, and very long paths break
    # ZipFile under C:\Users\...\Temp (Windows MAX_PATH).
    Get-ChildItem -LiteralPath $ProjectRoot -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like "datasets.bak.*" } |
        ForEach-Object {
            Write-Host "Excluding backup folder: $($_.Name)"
            $excludeDirs.Add($_.Name) | Out-Null
        }

    $xdArgs = @()
    foreach ($d in [string[]]$excludeDirs) {
        $xdArgs += "/XD"
        $xdArgs += $d
    }

    $xfArgs = @(
        "/XF",
        "*.zip",
        "*.pt",
        "*.pth",
        "Thumbs.db",
        ".DS_Store",
        # Android / JVM / local machine (never share)
        "local.properties",
        "hs_err_pid*.log",
        "replay_pid*.log",
        "*.hprof",
        # TFLite export calibration artifact (often huge; not needed for app source bundles)
        "calibration_image_sample_data*.npy",
        # Flutter verbose logs sometimes left in repo root
        "flutter*.log"
    )

    $rc = & robocopy.exe $ProjectRoot $staging /E /NFL /NDL /NJH /NJS /NC /NS /NP @xdArgs @xfArgs /LOG:$robolog
    if ($rc -ge 8) {
        Get-Content $robolog -Tail 40 -ErrorAction SilentlyContinue
        throw "robocopy failed with exit code $rc. Log: $robolog"
    }

    $yamlSrc = Join-Path $ProjectRoot "datasets\data.yaml"
    if (Test-Path $yamlSrc) {
        $dsOut = Join-Path $staging "datasets"
        New-Item -ItemType Directory -Path $dsOut -Force | Out-Null
        Copy-Item -Force $yamlSrc (Join-Path $dsOut "data.yaml")
        Set-Content -Path (Join-Path $dsOut "README.agent.txt") -Encoding utf8 -Value @"
Dataset images and labels are NOT included (too large for email/upload).
Paths in data.yaml are relative to this folder when you restore train/valid/test from Roboflow.
"@
    }

    $itemCount = (Get-ChildItem -LiteralPath $staging -Recurse -Force -ErrorAction SilentlyContinue | Measure-Object).Count
    if ($itemCount -lt 5) {
        throw "Staging looks empty ($itemCount items). Check robocopy log: $robolog"
    }

    if (Test-Path $OutputZip) {
        Remove-Item -LiteralPath $OutputZip -Force
    }

    $outDir = Split-Path -Parent $OutputZip
    if ($outDir -and -not (Test-Path $outDir)) {
        New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    }

    Write-Host "Zipping ($itemCount items under staging)..."
    [System.IO.Compression.ZipFile]::CreateFromDirectory(
        $staging,
        $OutputZip,
        [System.IO.Compression.CompressionLevel]::Optimal,
        $false
    )

    $sizeMb = [math]::Round((Get-Item -LiteralPath $OutputZip).Length / 1MB, 2)
    Write-Host ""
    Write-Host "Done: $OutputZip ($sizeMb MB)"

    if ($sizeMb -gt 500) {
        Write-Warning "Archive is over 500 MB. Exclude more paths in this script or remove large folders."
    }
}
catch {
    Write-Host ""
    Write-Host "FAILED: $_" -ForegroundColor Red
    if (Test-Path $robolog) {
        Write-Host "Robocopy log tail:" -ForegroundColor Yellow
        Get-Content $robolog -Tail 25 -ErrorAction SilentlyContinue
    }
    exit 1
}
finally {
    if (Test-Path $staging) {
        Remove-Item -LiteralPath $staging -Recurse -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path $robolog) {
        Remove-Item -LiteralPath $robolog -Force -ErrorAction SilentlyContinue
    }
}
